update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,184 +1,157 @@
 #!/usr/bin/env bash
-# bin/compile <build-dir> <cache-dir> <env-dir>
 
-set -e # immediately exit on error
-unset GIT_DIR	# Avoid GIT_DIR leak from previous build steps
+set -e            # fail fast
+set -o pipefail   # don't ignore exit codes when piping output
+# set -x          # enable debugging
 
-### Configure directories
-
-BUILD_DIR=${1:-}
-CACHE_DIR=${2:-}
-ENV_DIR=${3:-}
-BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
-# $BP_DIR/compile-extensions/bin/check_stack_support
-
-mkdir -p "$BUILD_DIR/.heroku/node/"
-cd $BUILD_DIR
-export PATH="$BUILD_DIR/.heroku/node/bin":$PATH
+# Configure directories
+build_dir=$1
+cache_dir=$2
+env_dir=$3
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
 
 # CF Common
-export BUILDPACK_PATH=$BP_DIR
-# source $BP_DIR/compile-extensions/lib/common
+export BUILDPACK_PATH=$bp_dir
+source $bp_dir/compile-extensions/lib/common
 # END CF Common
 
+# Load some convenience functions like status(), echo(), and indent()
+source $bp_dir/bin/common.sh
 
-### Compile
+# Fix leak
+status "Resetting git environment"
+unset GIT_DIR
 
-write_profile() {
-  local bp_dir="$1"
-  local build_dir="$2"
-  mkdir -p $build_dir/.profile.d
-  cp $bp_dir/profile/* $build_dir/.profile.d/
-}
+# Output npm debug info on error
+trap cat_npm_debug_log ERR
 
-export_env_dir() {
-  local env_dir=$1
-  if [ -d "$env_dir" ]; then
-    local whitelist_regex=${2:-''}
-    local blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH|LANG)$'}
-    if [ -d "$env_dir" ]; then
-      for e in $(ls $env_dir); do
-        echo "$e" | grep -E "$whitelist_regex" | grep -qvE "$blacklist_regex" &&
-        export "$e=$(cat $env_dir/$e)"
-        :
-      done
-    fi
-  fi
-}
+# Look in package.json's engines.node field for a semver range
+semver_range=$(cat $build_dir/package.json | $bp_dir/vendor/jq -r .engines.node)
 
-create_default_env() {
-  export NPM_CONFIG_PRODUCTION=${NPM_CONFIG_PRODUCTION:-true}
-  export NPM_CONFIG_LOGLEVEL=${NPM_CONFIG_LOGLEVEL:-error}
-  export NODE_MODULES_CACHE=${NODE_MODULES_CACHE:-true}
-  export NODE_ENV=${NODE_ENV:-production}
-}
+# Resolve node version using semver.io
+if is_cached
+then
+  node_version=$($bp_dir/bin/node $bp_dir/lib/version_resolver.js "$semver_range")
+else
+  node_version=$(curl --silent --get --data-urlencode "range=${semver_range}" https://semver.io/node/resolve)
+fi
 
-create_env() {
-  # write_profile "$BP_DIR" "$BUILD_DIR"
-  export_env_dir "$ENV_DIR"
-  create_default_env
-}
-
-create_env
-
-needs_resolution() {
-  local semver=$1
-  if ! [[ "$semver" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-    return 0
-  else
-    return 1
-  fi
-}
-
-download_failed() {
-  echo "We're unable to download the version of npm you've provided (${1})."
-  echo "Please remove the npm version specification in package.json"
+# Exit if no possible node version found
+if [ "$node_version" == "" ]; then
+  status "Node Engine matching $semver_range is not provided by this buildpack. Please upgrade your buildpack to receive the latest resources."
   exit 1
-}
+fi
 
-get_os() {
-  uname | tr A-Z a-z
-}
+# Recommend using semver ranges in a safe manner
+if [ "$semver_range" == "null" ]; then
+  protip "Specify a node version in package.json"
+  semver_range=""
+elif [ "$semver_range" == "*" ]; then
+  protip "Avoid using semver ranges like '*' in engines.node"
+elif [ ${semver_range:0:1} == ">" ]; then
+  protip "Avoid using semver ranges starting with '>' in engines.node"
+fi
 
-get_cpu() {
-  if [[ "$(uname -p)" = "i686" ]]; then
-    echo "x86"
+# Output info about requested range and resolved node version
+if [ "$semver_range" == "" ]; then
+  status "Defaulting to latest stable node: $node_version"
+else
+  status "Requested node range:  $semver_range"
+  status "Resolved node version: $node_version"
+fi
+
+# Download node from Heroku's S3 mirror of nodejs.org/dist
+status "Downloading and installing node"
+node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
+(curl `translate_dependency_url $node_url` -s --fail -o - | tar xzf - -C $build_dir)  || (echo -e "\n-----> Resource $node_url does not exist." 1>&2 ; exit 22)
+
+# Move node (and npm) into ./vendor and make them executable
+mkdir -p $build_dir/vendor
+mv $build_dir/node-v$node_version-linux-x64 $build_dir/vendor/node
+chmod +x $build_dir/vendor/node/bin/*
+PATH=$build_dir/vendor/node/bin:$PATH
+
+# Run subsequent node/npm commands from the build path
+cd $build_dir
+
+# If node_modules directory is checked into source control then
+# rebuild any native deps. Otherwise, restore from the build cache.
+if test -d $build_dir/node_modules; then
+  status "Found existing node_modules directory; skipping cache"
+  status "Rebuilding any native dependencies"
+  npm rebuild 2>&1 | indent
+elif test -d $cache_dir/node/node_modules; then
+  status "Restoring node_modules directory from cache"
+  cp -r $cache_dir/node/node_modules $build_dir/
+
+  status "Pruning cached dependencies not specified in package.json"
+  npm prune --production 2>&1 | indent
+
+  if test -f $cache_dir/node/.heroku/node-version && [ $(cat $cache_dir/node/.heroku/node-version) != "$node_version" ]; then
+    status "Node version changed since last build; rebuilding dependencies"
+    npm rebuild 2>&1 | indent
+  fi
+
+fi
+
+# Scope config var availability only to `npm install`
+(
+  if [ -d "$env_dir" ]; then
+    status "Exporting config vars to environment"
+    export_env_dir $env_dir
+  fi
+
+  status "Installing dependencies"
+  # Make npm output to STDOUT instead of its default STDERR
+  npm install --userconfig $build_dir/.npmrc --production 2>&1 | indent
+)
+
+# Persist goodies like node-version in the slug
+mkdir -p $build_dir/.heroku
+
+# Save resolved node version in the slug for later reference
+echo $node_version > $build_dir/.heroku/node-version
+
+# Purge node-related cached content, being careful not to purge the top-level
+# cache, for the sake of heroku-buildpack-multi apps.
+rm -rf $cache_dir/node_modules # (for apps still on the older caching strategy)
+rm -rf $cache_dir/node
+mkdir -p $cache_dir/node
+
+# If app has a node_modules directory, cache it.
+if test -d $build_dir/node_modules; then
+  status "Caching node_modules directory for future builds"
+  cp -r $build_dir/node_modules $cache_dir/node
+fi
+
+# Copy goodies to the cache
+cp -r $build_dir/.heroku $cache_dir/node
+
+status "Cleaning up node-gyp and npm artifacts"
+rm -rf "$build_dir/.node-gyp"
+rm -rf "$build_dir/.npm"
+
+# If Procfile is absent, try to create one using `npm start`
+if [ ! -e $build_dir/Procfile ]; then
+  npm_start=$(cat $build_dir/package.json | $bp_dir/vendor/jq -r .scripts.start)
+
+  # If `scripts.start` is set in package.json, or a server.js file
+  # is present in the app root, then create a default Procfile
+  if [ "$npm_start" != "null" ] || [ -f $build_dir/server.js ]; then
+    status "No Procfile found; Adding npm start to new Procfile"
+    echo "web: npm start" > $build_dir/Procfile
   else
-    echo "x64"
+    status "Procfile not found and npm start script is undefined"
+    protip "Create a Procfile or specify a start script in package.json"
   fi
-}
+fi
 
-os=$(get_os)
-cpu=$(get_cpu)
-export JQ="$BP_DIR/vendor/jq-$os"
+# Add SOX binary and libraries to path
+status "Adding SOX library support"
+tar xzf $bp_dir/vendor/sox.tar.gz -C $build_dir/vendor/
 
-read_json() {
-  local file=$1
-  local key=$2
-  if test -f $file; then
-    cat $file | $JQ --raw-output "$key // \"\"" || return 1
-  else
-    echo ""
-  fi
-}
-
-install_nodejs() {
-  local requested_version="$1"
-  local resolved_version=$requested_version
-  local dir="$2"
-
-  if needs_resolution "$requested_version"; then
-    BP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
-    versions_as_json=$(ruby -e "require 'yaml'; print YAML.load_file('$BP_DIR/manifest.yml')['dependencies'].select {|dep| dep['name'] == 'node' }.map {|dep| dep['version']}")
-    stable_major_version=4
-    resolved_version=$($BP_DIR/bin/node $BP_DIR/lib/version_resolver.js "$requested_version" "$versions_as_json" "$stable_major_version")
-  fi
-
-  if [[ "$resolved_version" = "undefined" ]]; then
-    echo "Downloading and installing node $requested_version..."
-  else
-    echo "Downloading and installing node $resolved_version..."
-  fi
-  local download_url="https://s3pository.heroku.com/node/v$resolved_version/node-v$resolved_version-$os-$cpu.tar.gz"
-  curl "`translate_dependency_url $download_url`" --silent --fail --retry 5 --retry-max-time 15 -o /tmp/node.tar.gz || (>&2 $BP_DIR/compile-extensions/bin/recommend_dependency $download_url && false)
-  echo "Downloaded [`translate_dependency_url $download_url`]"
-  tar xzf /tmp/node.tar.gz -C /tmp
-  rm -rf $dir/*
-  mv /tmp/node-v$resolved_version-$os-$cpu/* $dir
-  chmod +x $dir/bin/*
-}
-
-install_npm() {
-  local version="$1"
-
-  if [ "$version" == "" ]; then
-    echo "Using default npm version: `npm --version`"
-  else
-    if needs_resolution "$version"; then
-      echo "Resolving npm version ${version} via semver.io..."
-      version=$(curl --silent --get --retry 5 --retry-max-time 15 --data-urlencode "range=${version}" https://semver.herokuapp.com/npm/resolve || echo failed)
-      if [ "$version" = "failed" ]; then
-        download_failed $1
-      fi
-    fi
-    if [[ `npm --version` == "$version" ]]; then
-      echo "npm `npm --version` already installed with node"
-    else
-      echo "Downloading and installing npm $version (replacing version `npm --version`)..."
-      npm install --unsafe-perm --quiet -g npm@$version 2>&1 >/dev/null || download_failed $version
-    fi
-  fi
-}
-
-install_bins() {
-  local node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
-  local npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
-
-  install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
-  install_npm "$npm_engine" "$BUILD_DIR/.heroku/node"
-}
-
-install_bins
-
-install_node_modules() {
-  local build_dir=${1:-}
-
-  if [ -e $build_dir/package.json ]; then
-    cd $build_dir
-
-    if [ -e $build_dir/npm-shrinkwrap.json ]; then
-      echo "Installing node modules (package.json + shrinkwrap)"
-    else
-      echo "Installing node modules (package.json)"
-    fi
-    npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1
-  else
-    echo "Skipping (no package.json)"
-  fi
-}
-
-build_dependencies() {
-    install_node_modules "$BUILD_DIR"
-}
-
-build_dependencies
+# Update the PATH
+status "Building runtime environment"
+mkdir -p $build_dir/.profile.d
+echo "export PATH=\"\$HOME/vendor/node/bin:\$HOME/bin:\$HOME/node_modules/.bin:\$HOME/vendor/:\$PATH\";" > $build_dir/.profile.d/nodejs.sh
+echo "export LD_LIBRARY_PATH=\"\$HOME/vendor/libs/\";" >> $build_dir/.profile.d/nodejs.sh
